### ISSUE TITLE
Create an unabbreviateNumber() method

### ISSUE THREAD

**Issue by jackdomleo7** [moh3n9595/js-abbreviation-number#17]
**Is your feature request related to a problem? Please describe.**
I think it may also be useful to include a `unabbreviateNumber()` method as it may be fairly likely that developers want to convert an abbreviated number into a raw number. E.g. 

```typescript
unabbreviateNumber('12k') // 12000
unabbreviateNumber('1.4k') // 1400
```

**Describe the solution you'd like**
A method to unabbreviate a number

**Describe alternatives you've considered**
I've tried creating my own in the project(s) I'm using this package, but would be good to see it in here.

**Additional context**
Just an idea

**Comment by M0rteza-M** [comment]
I have written the function that you, @ jackdomleo7, suggested and it will be added to the project in a few hours. This is a function for developers who want to convert an abbreviated number to a raw number such as 10K to 10,000, as you said. Thanks for your suggestion.

**Comment by moh3n9595** [comment]
v1.4.0 is out, thanks @M0rteza-M!

**Comment by jackdomleo7** [comment]
Awesome!!
