### ISSUE TITLE
RFE: should support inserting a space between the number and the unit

### ISSUE THREAD

**Issue by kaiyoma** [moh3n9595/js-abbreviation-number#28]
When rendering units, like "35 MB", it's customary to insert a space between the number and the unit. It would be nice if this library supported that.

**Comment by moh3n9595** [comment]
You can customize the symbols array with something like this: `["", " kB", " MB", ...]`. Is enough for your purpose?

**Comment by kaiyoma** [comment]
Ah yes, that's a good point. 😄
