### ISSUE TITLE
داش دمت گرم

### ISSUE THREAD

**Issue by amirparsadd** [moh3n9595/js-abbreviation-number#37]
تابحال فکر نمی کردم ایرانی ها هم انقدر به اوپن سورس اهمیت بدن. خیلی تو پروژم کمکم کردی. موفق باشی💪🚀

**Comment by moh3n9595** [comment]
Hi @amirparsadd jan,
Thank you for your warm and heartfelt message. I am delighted that my project has been useful in your work. I hope you always succeed.
